#!/usr/bin/env bash
# installs and configures haproxy to a server
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.0 -y
sudo apt-get -y update
sudo apt-get install -y haproxy=2.0.\*
sudo echo "ENABLED=1" | sudo tee -a  /etc/default/haproxy
sudo echo "
frontend my-proxy
	bind *:80
	mode http
	default_backend web_servers" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo echo "
backend web_servers
	balance roundrobin
	mode http
	server web-01 54.237.98.199:80 check
	server web-02 100.26.152.160:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
